examples:
  - OC(=O)c1ccc(cc1)C(O)=O
  - OC(=O)c1cc(O)c(cc1O)C(O)=O
  - OC(=O)CCC(=O)O
  - OC(=O)C=C(C(=O)O)c1ccccc1
  - OC(=O)c1ccc(C=C)cc1C(=O)O
  - OC(=O)c1ccc(CN)cc1C(=O)O
  - OC(=O)c1ccncc1C(=O)O
  - OC(=O)c1ccco1C(=O)O
  - OC(=O)c1cccc(Br)c1C(=O)O
  - OC(=O)c1ccc(C#C)cc1C(=O)O
  - OC(=O)c1ccc2c(c1)ccc(c2)C(=O)O
  - OC(=O)COC(=O)CO
  - OC(=O)c1cc(CF3)ccc1C(=O)O
  - OC(=O)c1ccc(C(F)(F)F)cc1C(=O)O
  - OC(=O)CCCCCC(=O)O
  - OC(=O)CC(O)C(=O)O
  - OC(=O)C1CCC(CC1)C(=O)O
  - OC(=O)c1ccc(CN(CC)CC)cc1C(=O)O
  - OC(=O)c1cc(O)cc(O)c1C(=O)O
  - OC(=O)c1ccccc1C(=O)O
  - OC(=O)c1ccc(CN=C=O)cc1C(=O)O
  - OC(=O)CC(CN)C(=O)O
  - OC(=O)C1=CC=CN=C1C(=O)O
  - OC(=O)C1=CC=C(S1)C(=O)O
  - OC(=O)c1c(F)ccc(F)c1C(=O)O
  - OC(=O)c1ccc(Cl)cc1C(=O)O
  - OC(=O)c1ccc(CO)cc1C(=O)O
  - OC(=O)c1cc(N)ccc1C(=O)O
  - OC(=O)c1cc(C#N)ccc1C(=O)O
  - OC(=O)C=C(C(=O)O)c1ccccc1
  - OC(=O)c1cccc(N(=O)=O)c1C(=O)O
  - OC(=O)C(C(=O)O)c1ccccc1
  - OC(=O)c1ccc(COC(=O)C2=CC=CC=C2)cc1C(=O)O
  - OC(=O)C1=C(C(=O)O)C=CC=C1
  - OC(=O)c1ccc(C(C(=O)O)C(=O)O)cc1
  - OC(=O)c1ccc2c(c1)cccn2C(=O)O
  - OC(=O)C1=CC2=C(C=C1)C=CC=C2C(=O)O
  - OC(=O)c1cc(COC(=O)C(=O)O)ccc1
  - OC(=O)C1=CC=CC=C1COC(=O)O
  - OC(=O)C1=CN=CN=C1C(=O)O
  - OC(=O)CC1=CC=CC=C1C(=O)O
  - OC(=O)c1cccc(CO)c1C(=O)O
  - OC(=O)c1ccc(C(=O)O)c(C(=O)O)c1
  - OC(=O)CC(C(=O)O)C1=CC=CC=C1
  - OC(=O)c1ccc2ccc(C(=O)O)cc2c1
  - OC(=O)c1ccc(C(N)=O)cc1C(=O)O
  - OC(=O)C1=C(O)C=CC=C1C(=O)O
  - OC(=O)c1cccc(C(=O)O)c1O
  - OC(=O)C(C(=O)O)COC(=O)C(=O)O
